### ISSUE TITLE
sbt/sbt issue: Invalid or corrupt jarfile sbt/sbt-launch-0.13.6.jar

### ISSUE THREAD

**Issue by hbutani** [databricks/spark-csv#114]
Did a git clone and ran
sbt/sbt compile

I get:
Executing command line:
java
-Xms2048m
-Xmx2048m
-XX:MaxPermSize=512m
-XX:ReservedCodeCacheSize=256m
-jar
sbt/sbt-launch-0.13.6.jar
compile

**Error: Invalid or corrupt jarfile sbt/sbt-launch-0.13.6.jar**

Some more context:
- so far I had being using a local install of sbt (0.13.6). Running  sbt compile works just fine, with sbt pointing to my local sbt install.
- I get the same behavior in my spark-datetime package.  So probably not a spark-csv issue. Should I be filing an issue in spark-packages repo?

**Comment by varadharajan** [comment]
I'm facing this issue as well.

**Comment by jrpilat** [comment]
## Problem 1
sbt/sbt-launch-lib.bash contains:
```
URL1=http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/${SBT_VERSION}/sbt-launch.jar
URL2=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/${SBT_VERSION}/sbt-launch.jar
```
__${SBT_VERSION}__ is 0.13.6, according to project/build.properties.
__http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.6/sbt-launch.jar__ does not exist, and returns a 404, which is literally saved into the file __sbt/sbt-launch-0.13.6.jar__.

For a temporary workaround, comment out URL1 in the file mentioned above.
URL2, aka __http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.6/sbt-launch.jar__ does, in fact, exist.

## Problem 2
sbt-launch-lib.bash contains:
```
(curl --silent ${URL1} > "${JAR_DL}" || curl --silent ${URL2} > "${JAR_DL}") && mv "${JAR_DL}" "${JAR}"
```
__URL2__ contains a 302 redirect, and curl will literally download the "302 Found" response, rather than the jar file.

**Comment by brkyvz** [comment]
The typesafe repositories changed. You would need to make the changes shown here:
remove both URLs and add this
`URL1=https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/${SBT_VERSION}/sbt-launch.jar`

**Comment by hbutani** [comment]
Thanks, adding -L to the curl command, and using the URL suggested by @brkyvz  worked for me.
